@startuml FaleConosco - Contêineres

title C4 - Diagrama de Contêineres - Fale Conosco

!include <C4/C4_Container.puml>


' Pessoas
Person(solicitante, "Solicitante", "Usuário que busca e solicita um serviço ou atendimento.")
Person(atendente, "Atendente", "Colaborador responsável por interagir e concluir os atendimentos.")
Person(gestor, "Gestor", "Supervisor responsável pela unidade e gestão da equipe.")
Person(admin, "Administrador", "Equipe técnica para operação e manutenção do sistema.")

' Sistema Externo
System_Ext(auth_system, "Sistema de Autenticação", "Sistema corporativo que gerencia identidades e perfis dos usuários.") 


System_Boundary(faleconosco, "Sistema Fale Conosco") {

' Frontend
Container(portal_solic, "Portal do Solicitante", "Aplicação Web", "Interface pública para iniciar/solicitar atendimentos.")
 Container(app_backoffice, "Aplicação Backoffice", "Aplicação Web", "Interface para gestão de atendimentos e configurações.")

' Backend
Container(api, "API de Serviços", "Serviço Web", "Expõe a lógica de negócio, gerencia filas e comunica com sistemas externos.")

' Dados 
ContainerDb(db, "Base de Dados", "Relacional", "Armazena dados de atendimentos, usuários e configurações.")
}


' Relacionamentos Internos

Rel(portal_solic, api, "Solicita Atendimento e Consulta Posição na Fila", "HTTPS/JSON")
Rel(app_backoffice, api, "Controla Fila, Realiza Chat e Gerencia Configurações", "HTTPS/JSON")
Rel_U(api, db, "Persiste Dados da Fila, Atendimentos e Configurações", "JDBC")





Rel(solicitante, portal_solic, "Usa para Iniciar Atendimento", "Interface Web")
Rel(atendente, app_backoffice, "Usa para Atender e Gerenciar Status", "Interface Web")
Rel(gestor, app_backoffice, "Usa para Monitorar Fila e Alocar Atendentes", "Interface Web")
Rel(admin, app_backoffice, "Usa para Operação e Manutenção Técnica", "Interface Web")

' API e Sistema de Autenticação
Rel_R(api, auth_system, "Autentica e Consulta Perfis de Gestores/Atendentes/Admins", "HTTPS")


SHOW_LEGEND()
@enduml